# Copyright (C) 2016-2026 Simon Josefsson

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

variables:
  GIT_DEPTH: 250

stages:
 - build
 - repro
 - test

default:
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
    - ./**/config.h
    - ./**/*.log
    - ./out/$CI_JOB_NAME_SLUG/**

.gnulib-fetch:
  script:
  - GNULIB_REVISION=2a288c048e2a23ea9cd8cbef9a60aa4ac82bdc3d
  - wget -nv https://gitlab.com/libidn/gnulib-mirror/-/archive/$GNULIB_REVISION/gnulib-mirror-$GNULIB_REVISION.tar.gz
  - gzip -cd gnulib-mirror-$GNULIB_REVISION.tar.gz | tar xf -
  - rm -fv gnulib-mirror-$GNULIB_REVISION.tar.gz
  - export GNULIB_SRCDIR=$PWD/gnulib-mirror-$GNULIB_REVISION
  - export PATH=$PWD/gnulib-mirror-$GNULIB_REVISION:$PATH

.save-artifacts:
  script:
  - (! command -v git > /dev/null) || git -C $CI_PROJECT_DIR status
  - (! command -v git > /dev/null) || git -C $CI_PROJECT_DIR diff --exit-code # nothing should change version controlled files
  - sha256sum *.tar.* || true
  - mkdir -pv $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/{src,log}
  - find . -name out -prune -o -name '*.log' -print -o -name 'config.h' -print | xargs --no-run-if-empty mv --backup=numbered -v -t $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/log || true
  - mv -v *-src.tar.* $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/src/ || true
  - mv -v *.tar.* $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/ || true

sast:
  stage: build
  variables:
    SAST_EXCLUDED_PATHS: liboath/gl, libpskc/gl
include:
- template: Security/SAST.gitlab-ci.yml

B-Guix:
  rules:
  - when: always # used by merge request jobs with 'needs' on this job
  image: registry.gitlab.com/debdistutils/guix/container:extra
  stage: build
  before_script:
  - cp -rL /gnu/store/*profile/etc/* /etc/
  - . /etc/profile
  - echo 'root:x:0:0:root:/:/bin/sh' > /etc/passwd
  - echo 'root:x:0:' > /etc/group
  - groupadd --system guixbuild
  - for i in $(seq -w 1 10); do useradd -g guixbuild -G guixbuild -d /var/empty -s $(command -v nologin) -c "Guix build user $i" --system guixbuilder$i; done
  - env LANG=C.UTF-8 guix-daemon --build-users-group=guixbuild &
  - guix archive --authorize < /share/guix/ci.guix.gnu.org.pub
  - guix archive --authorize < /share/guix/bordeaux.guix.gnu.org.pub
  - guix describe
  - guix install --verbosity=0 linux-pam
  - GUIX_PROFILE="//.guix-profile"
  - . "$GUIX_PROFILE/etc/profile"
  - . /etc/profile
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure --enable-gcc-warnings CPPFLAGS="$(pkg-config --cflags pam)" LDFLAGS="$(pkg-config --libs pam)"
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make V=1 dist
  - !reference [.save-artifacts, script]

B-gcc:
  tags: [ saas-linux-medium-amd64 ]
  image: gcc:latest
  stage: build
  before_script:
  - gcc --version
  - cat /etc/os-release
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -q --no-install-recommends wget ca-certificates make git autoconf automake libtool bison pkgconf libpam0g-dev libxml2-dev libxmlsec1-dev libxml2-utils help2man gengetopt patch valgrind
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure -C --enable-gcc-warnings CC="gcc -std=gnu2x -fsanitize=address,undefined -fno-sanitize-recover=all -fsanitize-address-use-after-scope" WARN_CFLAGS=-Werror --with-xmlsec-crypto-engine=no
  - time make -k syntax-check
  - time make V=1 VERBOSE=t -j$(nproc) -k check
  - grep '^PASS tst_totp_validate' liboath/tests/tst_totp_validate.log
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log
  - time make clean; rm config.cache
  - time ./configure -C --enable-gcc-warnings CC="gcc -std=c23 -D_POSIX_C_SOURCE=200112L -fsanitize=address,undefined -fno-sanitize-recover=all -fsanitize-address-use-after-scope" WARN_CFLAGS=-Werror --with-xmlsec-crypto-engine=no
  - time make V=1 VERBOSE=t -j$(nproc) -k check
  - grep '^PASS tst_totp_validate' liboath/tests/tst_totp_validate.log
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log
  - time make clean; rm config.cache
  - time eatmydata apt-get install -y -q --no-install-recommends datefudge
  - time ./configure -C --enable-gcc-warnings WARN_CFLAGS=-Werror
  - time make V=1 VERBOSE=t -j$(nproc) -k check
  - grep '^PASS tst_usersfile.sh' liboath/tests/tst_usersfile.log
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

B-clang:
  tags: [ saas-linux-medium-amd64 ]
  image: silkeh/clang:latest
  stage: build
  before_script:
  - clang --version
  - cat /etc/os-release
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -q --no-install-recommends wget ca-certificates make git autoconf automake libtool bison pkgconf libpam0g-dev libxml2-dev libxmlsec1-dev libxml2-utils help2man gengetopt patch valgrind
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure -C --enable-gcc-warnings CC="clang -std=gnu2x -gdwarf-4 -fsanitize=address,undefined -fno-sanitize-recover=all -fsanitize-address-use-after-scope" WARN_CFLAGS=-Werror --with-xmlsec-crypto-engine=no
  - time make -k syntax-check
  - time make V=1 VERBOSE=t -j$(nproc) -k check
  - grep '^PASS tst_totp_validate' liboath/tests/tst_totp_validate.log
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log
  - time make clean; rm config.cache
  - time ./configure -C --enable-gcc-warnings CC="clang -std=c23 -D_POSIX_C_SOURCE=200112L -gdwarf-4 -fsanitize=address,undefined -fno-sanitize-recover=all -fsanitize-address-use-after-scope" WARN_CFLAGS=-Werror --with-xmlsec-crypto-engine=no
  - time make V=1 VERBOSE=t -j$(nproc) -k check
  - grep '^PASS tst_totp_validate' liboath/tests/tst_totp_validate.log
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log
  - time make clean; rm config.cache
  - time eatmydata apt-get install -y -q --no-install-recommends datefudge
  - time ./configure -C --enable-gcc-warnings CC="clang -gdwarf-4" WARN_CFLAGS=-Werror
  - time make V=1 VERBOSE=t -j$(nproc) -k check
  - grep '^PASS tst_usersfile.sh' liboath/tests/tst_usersfile.log
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

B-AlmaLinux8:
  image: almalinux:8
  stage: build
  before_script:
  - |
    dnf -y install wget make git autoconf automake libtool bison diffutils patch
    dnf -y install pam-devel valgrind
    dnf -y --enablerepo=powertools install gtk-doc help2man
    dnf -y install libxml2-devel libtool-ltdl-devel
    dnf -y install --enablerepo=powertools xmlsec1-openssl-devel
    dnf -y install epel-release
    dnf -y --enablerepo=epel install faketime gengetopt
    dnf -y install --enablerepo=baseos-debuginfo libxml2-debuginfo
  script:
  - echo "--suppressions=$(pwd)/libpskc/tests/libpskc.supp" >> ~/.valgrindrc
  - !reference [.gnulib-fetch, script]
  - ./bootstrap
  - ./configure -C --enable-gtk-doc --enable-gcc-warnings --enable-root-tests --enable-valgrind-tests
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t
  - grep '^PASS tst_sign.sh' pskctool/tests/tst_sign.sh.log
  - make -j$(nproc) dist
  - !reference [.save-artifacts, script]

B-AlmaLinux9:
  image: almalinux:9
  stage: build
  before_script:
  - |
    dnf -y install wget make git autoconf automake libtool bison diffutils patch
    dnf -y install libxml2-devel
    dnf -y install pam-devel valgrind
    dnf -y install --enablerepo=crb gtk-doc help2man
    dnf -y install epel-release
    dnf -y install --enablerepo=epel gengetopt faketime indent
    dnf -y install --enablerepo=baseos-debuginfo libxml2-debuginfo
  script:
  - !reference [.gnulib-fetch, script]
  - ./bootstrap
  - mkdir b
  - cd b
  - ../configure -C --enable-gtk-doc --enable-gcc-warnings --enable-root-tests --enable-valgrind-tests
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t
  - grep '^SKIP tst_sign.sh' pskctool/tests/tst_sign.sh.log
  - make -j$(nproc) dist
  - !reference [.save-artifacts, script]

B-RockyLinux8:
  image: rockylinux:8
  stage: build
  before_script:
  - |
    dnf -y install wget make git autoconf automake libtool bison diffutils patch
    dnf -y install pam-devel valgrind
    dnf -y --enablerepo=powertools install gtk-doc help2man
    dnf -y install libxml2-devel libtool-ltdl-devel
    dnf -y install --enablerepo=powertools xmlsec1-openssl-devel
    dnf -y install epel-release
    dnf -y --enablerepo=epel install faketime gengetopt
    dnf -y install --enablerepo=baseos-debug libxml2-debuginfo
  script:
  - echo "--suppressions=$(pwd)/libpskc/tests/libpskc.supp" >> ~/.valgrindrc
  - !reference [.gnulib-fetch, script]
  - ./bootstrap
  - mkdir b
  - cd b
  - ../configure -C --enable-gtk-doc --enable-gcc-warnings --enable-root-tests --enable-valgrind-tests
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t
  - grep '^PASS tst_sign.sh' pskctool/tests/tst_sign.sh.log
  - make -j$(nproc) dist
  - !reference [.save-artifacts, script]

B-RockyLinux9:
  image: rockylinux:9
  stage: build
  before_script:
  - |
    dnf -y install wget make git autoconf automake libtool bison diffutils patch
    dnf -y install pam-devel valgrind
    dnf -y install libxml2-devel
    dnf -y install --enablerepo=crb gtk-doc help2man
    dnf -y install epel-release
    dnf -y install --enablerepo=epel gengetopt faketime
    dnf -y install --enablerepo=baseos-debug libxml2-debuginfo
  script:
  - !reference [.gnulib-fetch, script]
  - ./bootstrap
  - ./configure -C --enable-gtk-doc --enable-gcc-warnings --enable-root-tests --enable-valgrind-tests
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t
  - grep '^SKIP tst_sign.sh' pskctool/tests/tst_sign.sh.log
  - make -j$(nproc) dist
  - !reference [.save-artifacts, script]

.pureosdebian: &pureosdebian
  tags: [ saas-linux-medium-amd64 ]
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - cat /etc/os-release
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -q --no-install-recommends wget ca-certificates make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools gengetopt datefudge patch valgrind
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure -C --enable-gcc-warnings --enable-valgrind-tests
  - time make syntax-check
  - time make -j$(nproc) V=1 VERBOSE=t check
  - make -C liboath/man compare-makefile
  - make -C libpskc/man compare-makefile
  - time make -j$(nproc) V=1 VERBOSE=t distcheck
  - !reference [.save-artifacts, script]

B-PureOS10:
  image: pureos/byzantium:latest
  extends: .pureosdebian

B-Debian11:
  image: debian:11-slim
  extends: .pureosdebian

B-Devuan5:
  image: devuan/devuan:daedalus
  extends: .pureosdebian

B-Debian12:
  image: debian:12-slim
  extends: .pureosdebian

.trisquelubuntu: &trisquelubuntu
  tags: [ saas-linux-medium-amd64 ]
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - cat /etc/os-release
  - sed -i 's,http://archive.trisquel.info/trisquel,http://ftp.acc.umu.se/mirror/trisquel/packages,' /etc/apt/sources.list
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -q --no-install-recommends wget ca-certificates make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools gengetopt datefudge patch valgrind
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure -C --enable-gcc-warnings --enable-valgrind-tests
  - time make syntax-check
  - time make -j$(nproc) V=1 VERBOSE=t check
  - make -C liboath/man compare-makefile
  - make -C libpskc/man compare-makefile
  - time make -j$(nproc) V=1 VERBOSE=t distcheck
  - !reference [.save-artifacts, script]

B-Ubuntu2204:
  image: ubuntu:22.04
  extends: .trisquelubuntu

B-Trisquel11:
  image: kpengboy/trisquel:11.0
  extends: .trisquelubuntu

Website:
  image: kpengboy/trisquel:11.0
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - sed -i 's,http://archive.trisquel.info/trisquel,http://ftp.acc.umu.se/mirror/trisquel/packages,' /etc/apt/sources.list
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -q --no-install-recommends wget ca-certificates make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools gengetopt datefudge patch
  - time eatmydata env DEBIAN_FRONTEND=noninteractive apt-get install -y -q asciidoc groff xsltproc
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure --enable-gcc-warnings -C --enable-gtk-doc --enable-gtk-doc-pdf
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t
  - grep '^PASS tst_usersfile.sh' liboath/tests/tst_usersfile.log
  - make -j$(nproc) dist
  - cd website; ./build-website.sh; cd ..
  - !reference [.save-artifacts, script]
  - mv -v website/html out/$CI_JOB_NAME_SLUG/

B-Debian13-arm64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: debian:trixie-slim
  tags: [ saas-linux-medium-arm64 ]
  stage: build
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq wget make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools gengetopt indent
  script:
  - !reference [.gnulib-fetch, script]
  - ./bootstrap
  - ./configure -C --enable-gcc-warnings
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t

B-Ubuntu2204-ppc64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: ubuntu:22.04
  tags: [ ppc64 ]
  stage: build
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq wget make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools gengetopt
  script:
  - !reference [.gnulib-fetch, script]
  - ./bootstrap
  - ./configure -C --enable-gcc-warnings
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t

B-Debian13-coverage:
  image: debian:13-slim
  stage: build
  before_script:
  - apt-get update -qq
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq wget make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools valgrind gengetopt
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq faketime lcov libpam-wrapper
  script:
  - echo "--suppressions=$(pwd)/libpskc/tests/libpskc.supp" >> ~/.valgrindrc
  - !reference [.gnulib-fetch, script]
  - ./bootstrap
  - ./configure -C --enable-gcc-warnings --enable-root-tests --enable-valgrind-tests CFLAGS="-g --coverage"
  - make init-coverage
  - make -j$(nproc) V=1 VERBOSE=t build-coverage
  - grep '^PASS tst_usersfile.sh' liboath/tests/tst_usersfile.log
  - grep '^PASS run-root-tests.sh' pam_oath/tests/run-root-tests.sh.log
  - lcov --remove doc/coverage/oath-toolkit.info '/usr/include/*' '*/liboath/gl/*' '*/liboath/tests/*' '*/libpskc/gl/*' '*/libpskc/tests/*' '*/pam_oath/tests/*' -o doc/coverage/oath-toolkit-filtered.info
  - make gen-coverage PACKAGE=oath-toolkit-filtered
  - !reference [.save-artifacts, script]
  - mv doc/coverage/ out/$CI_JOB_NAME_SLUG/

B-Fedora39-clanganalyzer:
  image: fedora:39
  stage: build
  before_script:
  - dnf update -y
  - dnf install -y wget make patch git autoconf automake libtool bison pam-devel xmlsec1-openssl-devel libtool-ltdl-devel libxml2-devel help2man gtk-doc valgrind gengetopt
  - dnf install -y datefudge clang clang-analyzer
  script:
  - !reference [.gnulib-fetch, script]
  - ./bootstrap
  - scan-build ./configure -C --with-xmlsec-crypto-engine=openssl
  - scan-build -o clang-analyzer make -j$(nproc) V=1
  - !reference [.save-artifacts, script]
  - mv clang-analyzer/ out/$CI_JOB_NAME_SLUG/

# https://clang.llvm.org/docs/AddressSanitizer.html
# https://github.com/google/sanitizers/wiki/AddressSanitizer
# https://github.com/google/sanitizers/wiki/AddressSanitizerFlags
# https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
# https://clang.llvm.org/docs/LeakSanitizer.html
# https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer
# https://lists.gnu.org/archive/html/bug-gnulib/2022-03/msg00016.html
B-F41-clang-Sanitizer:
  image: fedora:41
  stage: build
  before_script:
  - time dnf -y update
  - time dnf install -y wget make patch git autoconf automake libtool bison pam-devel libxml2-devel help2man valgrind gengetopt
  - time dnf install -y clang
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time env ASAN_OPTIONS=detect_leaks=0 ./configure -C --enable-gcc-warnings CC=clang CFLAGS="-g -O0 -fsanitize=undefined -fsanitize=address -fno-sanitize-recover=all -fsanitize-address-use-after-scope -D_FORTIFY_SOURCE=0"
  - time env ASAN_OPTIONS=detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1 make check VERBOSE=t V=1
  - grep '^PASS tst_oathtool' oathtool/tests/tst_oathtool.sh.log
  - grep '^PASS tst_validate' libpskc/tests/tst_validate.log
  - make clean; rm config.cache
  - time env ASAN_OPTIONS=detect_leaks=0 ./configure -C --enable-gcc-warnings CC=clang CFLAGS="-g -O1 -fsanitize=undefined -fsanitize=address -fno-sanitize-recover=all -fsanitize-address-use-after-scope"
  - time env ASAN_OPTIONS=detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1 make check VERBOSE=t V=1
  - grep '^PASS tst_oathtool' oathtool/tests/tst_oathtool.sh.log
  - grep '^PASS tst_validate' libpskc/tests/tst_validate.log
  - make clean; rm config.cache
  - time env ASAN_OPTIONS=detect_leaks=0 ./configure -C --enable-gcc-warnings CC=clang CFLAGS="-g -O2 -fsanitize=undefined -fsanitize=address -fno-sanitize-recover=all -fsanitize-address-use-after-scope"
  - time env ASAN_OPTIONS=detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1 make check VERBOSE=t V=1
  - grep '^PASS tst_oathtool' oathtool/tests/tst_oathtool.sh.log
  - grep '^PASS tst_validate' libpskc/tests/tst_validate.log

Fedora-rawhide:
  image: fedora:rawhide
  stage: test
  needs: [B-Guix]
  before_script:
  - dnf install -y make gcc diffutils file pam-devel
  - dnf install -y libxml2-devel xmlsec1-devel xmlsec1-openssl libtool-ltdl-devel
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure -C --enable-gcc-warnings --with-xmlsec-crypto-engine=no
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^SKIP tst_sign.sh' pskctool/tests/tst_sign.sh.log

B-OpenBSD:
  tags: [ openbsd ]
  stage: build
  before_script:
  - id
  - uname -a
  - sysctl hw
  script:
  - !reference [.gnulib-fetch, script]
  - time env AUTOCONF_VERSION=2.72 AUTOMAKE_VERSION=1.18 ./bootstrap
  - time ./configure -C --enable-gcc-warnings --with-xmlsec-crypto-engine=gnutls
  - time make V=1
  - time make V=1 check VERBOSE=t
  - grep '^PASS tst_oathtool' oathtool/tests/tst_oathtool.sh.log
  - grep '^PASS tst_validate' libpskc/tests/tst_validate.log

# https://docs.gitlab.com/ci/runners/hosted_runners/macos/
B-macOS15Xcode16:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: macos-15-xcode-16
  tags: [ saas-macos-medium-m1 ]
  stage: build
  variables:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_UPGRADE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  before_script:
  - time brew install make gnu-tar autoconf automake libtool gengetopt bison help2man libxmlsec1
  script:
  - PATH="/opt/homebrew/opt/bison/bin:$PATH" # brew bison is keg-only
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure --enable-gcc-warnings
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) V=1
  - time make -j$(nproc) V=1 -k check VERBOSE=t
  - grep '^PASS tst_sign.sh' pskctool/tests/tst_sign.sh.log
  - PATH="$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH"
  - time env XML_CATALOG_FILES="$HOMEBREW_PREFIX/etc/xml/catalog" gmake V=1 dist
  - !reference [.save-artifacts, script]

B-macOS26Xcode26:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: macos-26-xcode-26
  tags: [ saas-macos-large-m2pro ]
  stage: build
  variables:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_UPGRADE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  before_script:
  - time brew install make gnu-tar autoconf automake libtool gengetopt bison help2man libxmlsec1
  script:
  - PATH="/opt/homebrew/opt/bison/bin:$PATH" # brew bison is keg-only
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure --enable-gcc-warnings
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) V=1
  - time make -j$(nproc) V=1 -k check VERBOSE=t
  - grep '^PASS tst_sign.sh' pskctool/tests/tst_sign.sh.log
  - PATH="$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH"
  - time env XML_CATALOG_FILES="$HOMEBREW_PREFIX/etc/xml/catalog" gmake V=1 dist
  - !reference [.save-artifacts, script]

# https://docs.gitlab.com/ci/runners/hosted_runners/windows/
B-Windows-UCRT64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  tags: [ saas-windows-medium-amd64 ]
  stage: build
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe -nv --no-check-certificate -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - Get-FileHash ./msys2.exe -Algorithm SHA256 | Format-List
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'UCRT64' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu git autoconf automake libtool patch make mingw-w64-ucrt-x86_64-gcc bison gtk-doc gengetopt help2man
    # https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
    git status
    git describe
    file configure.ac
    git config --global core.autocrlf false
    git config --global core.eol lf
    git rm -rf --cached . | tail
    git reset --hard HEAD
    git status
    git describe
    file configure.ac
    GNULIB_REVISION=$(grep GNULIB_REVISION=[0-9a-f] .gitlab-ci.yml | sed s,.*GNULIB_REVISION=,,)
    wget -nv https://gitlab.com/libidn/gnulib-mirror/-/archive/$GNULIB_REVISION/gnulib-mirror-$GNULIB_REVISION.tar.gz
    tar xfa gnulib-mirror-$GNULIB_REVISION.tar.gz
    rm -fv gnulib-mirror-$GNULIB_REVISION.tar.gz
    export GNULIB_SRCDIR=gnulib-mirror-$GNULIB_REVISION
    export PATH=$PWD/gnulib-mirror-$GNULIB_REVISION:$PATH
    ./bootstrap
    ./configure -C --enable-gcc-warnings
    make -j$(nproc) V=1 -k check VERBOSE=t'
  - C:\msys64\usr\bin\bash -lc 'grep ^PASS liboath/tests/tst_totp_validate.log'

Windows-MINGW64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  tags: [ saas-windows-medium-amd64 ]
  stage: test
  needs: [B-Guix]
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe -nv --no-check-certificate -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - Get-FileHash ./msys2.exe -Algorithm SHA256 | Format-List
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'MINGW64' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu make diffutils mingw-w64-x86_64-gcc
    tar xfa out/b-guix/oath-toolkit-*.tar.gz
    cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
    ./configure -C --enable-gcc-warnings
    make -j$(nproc) V=1 -k check VERBOSE=t'
  - C:\msys64\usr\bin\bash -lc 'grep ^PASS oath-toolkit-*/liboath/tests/tst_totp_validate.log'

Windows-MSYS:
  allow_failure: true # gnulib wint_t issue, last worked in b1c8aaa5c
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  tags: [ saas-windows-medium-amd64 ]
  stage: test
  needs: [B-Guix]
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe -nv --no-check-certificate -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - Get-FileHash ./msys2.exe -Algorithm SHA256 | Format-List
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'MSYS' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu make diffutils gcc
    tar xfa out/b-guix/oath-toolkit-*.tar.gz
    cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
    ./configure -C --enable-gcc-warnings
    make -j$(nproc) V=1 -k check VERBOSE=t'
  - C:\msys64\usr\bin\bash -lc 'grep ^PASS oath-toolkit-*/liboath/tests/tst_totp_validate.log'

# https://www.synopsys.com/blogs/software-security/integrating-coverity-scan-with-gitlab-ci/
Coverity:
  rules:
  - if: $CI_COMMIT_REF_PROTECTED == "true"
  - when: manual
  image: debian:12-slim
  stage: build
  allow_failure: true
  before_script:
  - apt-get update -qq
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq wget make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools valgrind gengetopt
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq faketime lcov libpam-wrapper
  - apt-get install -y -q curl
  script:
  - test -n "$COVERITY_SCAN_TOKEN" && test -n "$COVERITY_SCAN_PROJECT_NAME"
  - curl -o /tmp/cov-analysis-linux64.tgz https://scan.coverity.com/download/linux64
    --form project="$COVERITY_SCAN_PROJECT_NAME" --form token="$COVERITY_SCAN_TOKEN"
  - md5sum /tmp/cov-analysis-linux64.tgz
  - tar xfz /tmp/cov-analysis-linux64.tgz
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure --enable-gcc-warnings --disable-doc --enable-root-tests CFLAGS="-g -Og"
  - cov-analysis-linux64-*/bin/cov-build --dir cov-int make check -j$(nproc)
  - tar cfz cov-int.tar.gz cov-int
  - curl https://scan.coverity.com/builds
    --form project="$COVERITY_SCAN_PROJECT_NAME"
    --form token="$COVERITY_SCAN_TOKEN" --form email="$GITLAB_USER_EMAIL"
    --form file=@cov-int.tar.gz --form version="`git describe --tags`"
    --form description="`git describe --tags` / $CI_COMMIT_TITLE / $CI_COMMIT_REF_NAME:$CI_PIPELINE_ID"
  artifacts:
    expire_in: 1 week
    paths:
      - cov-int/*.txt

0-compare:
  image: alpine:latest
  stage: repro
  needs: [ B-PureOS10, B-Debian11, B-Devuan5, B-Debian12, B-AlmaLinux8, B-AlmaLinux9, B-RockyLinux8, B-RockyLinux9, B-Trisquel11, B-Ubuntu2204, B-macOS15Xcode16, B-macOS26Xcode26, B-Guix, R-Guix, R-Debian12, R-Ubuntu2404, S-Trisquel10, S-Ubuntu2004, T-Trisquel10, T-Ubuntu2004 ]
  script:
  - cd out
  - sha256sum */*.tar.* */*/*.tar.* | sort | grep    -- -src.tar.
  - sha256sum */*.tar.* */*/*.tar.* | sort | grep -v -- -src.tar.
  - sha256sum */*.tar.* */*/*.tar.* | sort | uniq -c -w64 | sort -rn
  - sha256sum */*.tar.* */*/*.tar.* | grep    -- -src.tar. | sort | uniq -c -w64 | grep -v '^      1 '
  - sha256sum */*.tar.* */*/*.tar.* | grep -v -- -src.tar. | sort | uniq -c -w64 | grep -v '^      1 '
# Confirm modern git-archive tarball reproducibility
  - cmp b-almalinux8/src/*.tar.gz b-almalinux9/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-rockylinux8/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-rockylinux9/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-debian12/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-devuan5/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz r-guix/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz r-ubuntu2404/src/*v2.*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-macos15xcode16/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-macos26xcode26/src/*.tar.gz
# Confirm old git-archive (export-subst but long git describe) tarball reproducibility
  - cmp b-trisquel11/src/*.tar.gz b-ubuntu2204/src/*.tar.gz
# Confirm really old git-archive (no export-subst) tarball reproducibility
  - cmp b-debian11/src/*.tar.gz b-pureos10/src/*.tar.gz
# Confirm 'make dist' generated tarball reproducibility
  - cmp b-almalinux8/*.tar.gz b-rockylinux8/*.tar.gz
  - cmp b-almalinux9/*.tar.gz b-rockylinux9/*.tar.gz
  - cmp b-devuan5/*.tar.gz b-debian12/*.tar.gz
  - cmp b-guix/*.tar.gz r-guix/*.tar.gz
  - cmp b-pureos10/*.tar.gz b-debian11/*.tar.gz
  - cmp b-trisquel11/*.tar.gz b-ubuntu2204/*.tar.gz
  - cmp t-trisquel10/*.tar.gz t-ubuntu2004/*.tar.gz
  - cmp b-macos15xcode16/*.tar.gz b-macos26xcode26/*.tar.gz
# Confirm 'make dist' from git-archive tarball reproducibility
  - cmp s-trisquel10/*.tar.gz s-ubuntu2004/*.tar.gz
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
    - ./out/**

R-Guix:
  tags: [ saas-linux-medium-amd64 ]
  image: registry.gitlab.com/debdistutils/guix/container:extra
  stage: repro
  needs: []
  before_script:
  - cp -rL /gnu/store/*profile/etc/* /etc/
  - . /etc/profile
  - echo 'root:x:0:0:root:/:/bin/sh' > /etc/passwd
  - echo 'root:x:0:' > /etc/group
  - groupadd --system guixbuild
  - for i in $(seq -w 1 10); do useradd -g guixbuild -G guixbuild -d /var/empty -s $(command -v nologin) -c "Guix build user $i" --system guixbuilder$i; done
  - env LANG=C.UTF-8 guix-daemon --build-users-group=guixbuild &
  - guix archive --authorize < /share/guix/ci.guix.gnu.org.pub
  - guix archive --authorize < /share/guix/bordeaux.guix.gnu.org.pub
  - guix describe
  - guix install --verbosity=0 linux-pam
  - GUIX_PROFILE="//.guix-profile"
  - . "$GUIX_PROFILE/etc/profile"
  - . /etc/profile
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure --enable-gcc-warnings CPPFLAGS="$(pkg-config --cflags pam)" LDFLAGS="$(pkg-config --libs pam)"
  - time make V=1 syntax-check
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) dist V=1 VERBOSE=t
  - git status
  - git diff --exit-code
  - gpg --batch --passphrase '' --quick-gen-key pipeline@example.org
  - git checkout -B cibranch
  - git config user.email "pipeline@example.org"
  - git config user.name "Pipeline Builder"
  - git config user.signingkey pipeline@example.org
  - |
    if test -z "$CI_COMMIT_TAG"; then
      sed -i '3i * Noteworthy changes in release ?.? (????-??-??) [?]\n\n** WARNING This release was prepared automatically with no testing.\n' NEWS
      git commit -m "Warn about automatic release." NEWS
      relver='97.23.42'
      reltyp='alpha'
    else # maintainer ran release-commit
      relver=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\1/p' | head -1)
      reltyp=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\2/p' | head -1)
    fi
  - test "$relver" != "97.23.42" || make release-commit RELEASE="$relver $reltyp"
  - make release RELEASE="$relver $reltyp" V=1 VERBOSE=t
  - cat -n ~/announce-*
  - git diff --exit-code # nothing should change version controlled files
  - sha256sum *.tar.*
  - mkdir -pv out/$CI_JOB_NAME_SLUG/{src,rel,log}
  - find . -name out -prune -o -name '*.log' -print -o -name 'config.h' -print | xargs --no-run-if-empty mv --backup=numbered -v -t $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/log
  - test "$relver" != "97.23.42" || mv -v *97.23.42* out/$CI_JOB_NAME_SLUG/rel/
  - mv -v *-src.tar.* out/$CI_JOB_NAME_SLUG/src/
  - mv -v *.tar.* ~/announce-* out/$CI_JOB_NAME_SLUG/

R-Debian12:
  tags: [ saas-linux-medium-amd64 ]
  image: debian:12-slim
  stage: repro
  needs: []
  before_script:
  - cat /etc/os-release
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -qq wget make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools valgrind gengetopt libdigest-sha3-perl
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure --enable-gcc-warnings
  - time make syntax-check
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) dist V=1 VERBOSE=t
  - sha256sum *.tar.*
  - git status
  - git diff --exit-code
  - time apt-get install -y -q --no-install-recommends gpg gpgv2 gpg-agent
  - gpg --batch --passphrase '' --quick-gen-key pipeline@example.org
  - git checkout -B cibranch
  - git config user.email "pipeline@example.org"
  - git config user.name "Pipeline Builder"
  - git config user.signingkey pipeline@example.org
  - |
    if test -z "$CI_COMMIT_TAG"; then
      sed -i '3i * Noteworthy changes in release ?.? (????-??-??) [?]\n\n** WARNING This release was prepared automatically with no testing.\n' NEWS
      git commit -m "Warn about automatic release." NEWS
      relver='97.23.42'
      reltyp='alpha'
    else # maintainer ran release-commit
      relver=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\1/p' | head -1)
      reltyp=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\2/p' | head -1)
    fi
  - test "$relver" != "97.23.42" || make release-commit RELEASE="$relver $reltyp"
  - make release RELEASE="$relver $reltyp" V=1 VERBOSE=t
  - cat -n ~/announce-*
  - git diff --exit-code # nothing should change version controlled files
  - sha256sum *.tar.*
  - mkdir -pv out/$CI_JOB_NAME_SLUG/{src,rel,log}
  - find . -name out -prune -o -name '*.log' -print -o -name 'config.h' -print | xargs --no-run-if-empty mv --backup=numbered -v -t out/$CI_JOB_NAME_SLUG/log
  - test "$relver" != "97.23.42" || mv -v *97.23.42* out/$CI_JOB_NAME_SLUG/rel/
  - mv -v *-src.tar.* out/$CI_JOB_NAME_SLUG/src/
  - mv -v *.tar.* ~/announce-* out/$CI_JOB_NAME_SLUG/

R-Ubuntu2404:
  image: ubuntu:24.04
  tags: [ saas-linux-medium-amd64 ]
  stage: repro
  needs: []
  before_script:
  - cat /etc/os-release
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -qq wget make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools valgrind gengetopt libdigest-sha3-perl
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure --enable-gcc-warnings
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) dist
  - sha256sum *.tar.*
  - git status
  - git diff --exit-code # nothing should change version controlled files
  - apt-get install -y -q gpg gpgv
  - gpg --batch --passphrase '' --quick-gen-key pipeline@example.org
  - git checkout $CI_COMMIT_BRANCH
  - git config user.email "pipeline@example.org"
  - git config user.name "Pipeline Builder"
  - git config user.signingkey pipeline@example.org
  - |
    if test -z "$CI_COMMIT_TAG"; then
      sed -i '3i * Noteworthy changes in release ?.? (????-??-??) [?]\n\n** WARNING This release was prepared automatically with no testing.\n' NEWS
      git commit -m "Warn about automatic release." NEWS
      relver='97.23.42'
      reltyp='alpha'
    else # maintainer ran release-commit
      relver=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\1/p' | head -1)
      reltyp=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\2/p' | head -1)
    fi
  - test "$relver" != "97.23.42" || make release-commit RELEASE="$relver $reltyp"
  - make release RELEASE="$relver $reltyp" V=1 VERBOSE=t
  - cat -n ~/announce-*
  - git diff --exit-code # nothing should change version controlled files
  - sha256sum *.tar.*
  - mkdir -pv out/$CI_JOB_NAME_SLUG/{src,rel,log}
  - find . -name out -prune -o -name '*.log' -print -o -name 'config.h' -print | xargs --no-run-if-empty mv --backup=numbered -v -t out/$CI_JOB_NAME_SLUG/log
  - test "$relver" != "97.23.42" || mv -v *97.23.42* out/$CI_JOB_NAME_SLUG/rel/
  - mv -v *-src.tar.* out/$CI_JOB_NAME_SLUG/src/
  - mv -v *.tar.* ~/announce-* out/$CI_JOB_NAME_SLUG/

T-Trisquel10:
  tags: [ saas-linux-medium-amd64 ]
  image: docker.io/kpengboy/trisquel:10.0
  stage: repro
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - sed -i 's,http://archive.trisquel.info/trisquel,http://ftp.acc.umu.se/mirror/trisquel/packages,' /etc/apt/sources.list
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -q wget make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools valgrind gengetopt datefudge
  script:
  - mkdir -pv ../b
  - cd ../b
  - tar xfz ../*/out/b-guix/src/*-*.tar.gz
  - cd $(tar tfa ../*/out/b-guix/src/*-*.tar.gz | head -n1)
  - !reference [.gnulib-fetch, script]
  - time datefudge "5 years" ./bootstrap
  - time datefudge "5 years" ./configure --enable-gcc-warnings
  - time datefudge "5 years" make -j$(nproc)
  - time datefudge "5 years" make -j$(nproc) check V=1 VERBOSE=t
  - time datefudge "5 years" make -j$(nproc) distcheck
  - sha256sum *.tar.*
  - mkdir -pv $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/log
  - find . -name out -prune -o -name '*.log' -print -o -name 'config.h' -print | xargs --no-run-if-empty mv --backup=numbered -v -t $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/log
  - mv -v *.tar.* $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/

T-Ubuntu2004:
  tags: [ saas-linux-medium-amd64 ]
  image: ubuntu:20.04
  stage: repro
  needs: [B-Guix]
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - cat /etc/os-release
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -q wget make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools valgrind gengetopt datefudge
  script:
  - tar xfz out/b-guix/src/*-*.tar.gz
  - cd $(tar tfa out/b-guix/src/*-*.tar.gz | head -n1)
  - !reference [.gnulib-fetch, script]
  - time datefudge "5 years ago" ./bootstrap
  - time datefudge "5 years ago" ./configure --enable-gcc-warnings
  - time datefudge "5 years ago" make -j$(nproc) syntax-check
  - time datefudge "5 years ago" make -j$(nproc) check V=1 VERBOSE=t
  - time datefudge "5 years ago" make -j$(nproc) distcheck V=1 VERBOSE=t
  - sha256sum *.tar.*
  - mkdir -pv $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/log
  - find . -name out -prune -o -name '*.log' -print -o -name 'config.h' -print | xargs --no-run-if-empty mv --backup=numbered -v -t $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/log
  - mv -v *.tar.* $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/

S-Trisquel10:
  tags: [ saas-linux-medium-amd64 ]
  image: docker.io/kpengboy/trisquel:10.0
  stage: repro
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - sed -i 's,http://archive.trisquel.info/trisquel,http://ftp.acc.umu.se/mirror/trisquel/packages,' /etc/apt/sources.list
  - time apt-get update -y
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -q wget make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools valgrind gengetopt datefudge
  script:
  - mkdir -pv ../b
  - cd ../b
  - tar xfz ../*/out/b-guix/src/*-*.tar.gz
  - cd $(tar tfa ../*/out/b-guix/src/*-*.tar.gz | head -n1)
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure --enable-gcc-warnings
  - grep '^VERSION = ' Makefile | grep -v UNKNOWN
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) dist
  - sha256sum *.tar.*
  - mkdir -pv $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/{src,log}
  - find . -name out -prune -o -name '*.log' -print -o -name 'config.h' -print | xargs --no-run-if-empty mv --backup=numbered -v -t $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/log
  - mv -v *.tar.* $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/

S-Ubuntu2004:
  tags: [ saas-linux-medium-amd64 ]
  image: ubuntu:20.04
  stage: repro
  needs: [B-Guix]
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - cat /etc/os-release
  - time apt-get update -y
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y -q wget make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools valgrind gengetopt datefudge
  script:
  - tar xfz out/b-guix/src/*-*.tar.gz
  - cd $(tar tfa out/b-guix/src/*-*.tar.gz | head -n1)
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap
  - time ./configure --enable-gcc-warnings
  - grep '^VERSION = ' Makefile | grep -v UNKNOWN
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) dist
  - sha256sum *.tar.*
  - mkdir -pv ../out/$CI_JOB_NAME_SLUG/{src,log}
  - find . -name out -prune -o -name '*.log' -print -o -name 'config.h' -print | xargs --no-run-if-empty mv --backup=numbered -v -t $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/log
  - mv -v *.tar.* ../out/$CI_JOB_NAME_SLUG/

Debian12:
  image: debian:12-slim
  stage: test
  needs: [B-Guix]
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make gcc pkg-config libpam0g-dev libxmlsec1-dev libxml2-utils datefudge
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings --disable-valgrind-tests
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

Debian-testing:
  image: debian:testing-slim
  stage: test
  needs: [B-Guix]
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make gcc pkg-config libpam0g-dev libxmlsec1-dev libxml2-utils datefudge
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure --enable-gcc-warnings --disable-valgrind-tests
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

Ubuntu-rolling-ppc64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: ubuntu:rolling
  tags: [ ppc64 ]
  stage: test
  needs: [B-Guix]
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make gcc pkg-config libpam0g-dev libxml2-utils datefudge
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure -C --enable-gcc-warnings --disable-valgrind-tests
  - make -j$(nproc) check V=1 VERBOSE=t

Ubuntu-rolling-xmlsec:
  image: ubuntu:rolling
  stage: test
  needs: [B-Guix]
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make gcc pkg-config libpam0g-dev libxmlsec1-dev libxml2-utils datefudge
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure -C --enable-gcc-warnings --disable-valgrind-tests
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

Ubuntu-xmlsec:
  image: ubuntu:20.04
  stage: test
  needs: [B-Guix]
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make gcc pkg-config libpam0g-dev libxmlsec1-dev libxml2-utils datefudge
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings --disable-valgrind-tests
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_sign.sh' pskctool/tests/tst_sign.sh.log

AlmaLinux8-xmlsec:
  image: almalinux:8
  stage: test
  needs: [B-Guix]
  before_script:
  - yum -y install make gcc diffutils file pam-devel
  - yum -y install libxml2-devel libtool-ltdl-devel
  - dnf -y install epel-release
  - dnf -y install --enablerepo=powertools indent xmlsec1-openssl-devel
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure -C --enable-gcc-warnings --disable-valgrind-tests --with-xmlsec-crypto-engine=openssl
  - make -j$(nproc) syntax-check
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

AlmaLinux9-openssl:
  image: almalinux:9
  stage: test
  needs: [B-Guix]
  before_script:
  - dnf -y install make gcc diffutils file pam-devel openssl-devel
  - dnf -y install epel-release
  - dnf -y --enablerepo=crb install libtool-ltdl-devel indent
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure -C --enable-gcc-warnings --disable-valgrind-tests --with-openssl
  - make -j$(nproc) syntax-check
  - make -j$(nproc) check V=1 VERBOSE=t

RockyLinux9-ppc64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: rockylinux:9
  tags: [ ppc64 ]
  stage: test
  needs: [B-Guix]
  before_script:
  - dnf -y install make gcc diffutils file pam-devel
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure -C --enable-gcc-warnings
  - make -j$(nproc) check V=1 VERBOSE=t

Alpine-mold:
  image: alpine:latest
  stage: test
  needs: [B-Guix]
  before_script:
  - apk update
  - apk add build-base datefudge xmlsec-dev mold
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure -C --enable-gcc-warnings CC='cc -fuse-ld=mold'
  - make -j$(nproc) check V=1 VERBOSE=t 2>&1 | tee build.log
  - (! grep -E 'mold. warning' build.log)
  - grep 'mold ' libpskc/.libs/libpskc.so

Alpine-arm64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: alpine:latest
  tags: [ saas-linux-medium-arm64 ]
  stage: test
  needs: [B-Guix]
  before_script:
  - apk update
  - apk add build-base datefudge xmlsec-dev
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure -C --enable-gcc-warnings
  - make -j$(nproc) check V=1 VERBOSE=t

ArchLinux-xmlsec:
  image: archlinux:latest
  stage: test
  needs: [B-Guix]
  before_script:
  - pacman -Suy --noconfirm make gcc diffutils file xmlsec pkg-config
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

Fedora39-arm64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: fedora:39
  tags: [ saas-linux-medium-arm64 ]
  stage: test
  needs: [B-Guix]
  before_script:
  - dnf install -y make gcc diffutils file pam-devel
  - dnf install -y libxml2-devel xmlsec1-devel xmlsec1-openssl libtool-ltdl-devel
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure -C --enable-gcc-warnings
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_sign.sh' pskctool/tests/tst_sign.sh.log

Gentoo:
  image: gentoo/stage3
  stage: test
  needs: [B-Guix]
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings
  - make -j$(nproc) check V=1 VERBOSE=t

macOS:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  tags: [ saas-macos-medium-m1 ]
  stage: test
  needs: [B-Guix]
  variables:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_UPGRADE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  before_script:
  - time brew install libxmlsec1
  script:
  - gzip -cd out/b-guix/oath-toolkit-*.tar.gz | tar xf -
  - cd $(gzip -cd out/b-guix/oath-toolkit-*.tar.gz | tar tf - | head -n1)
  - mkdir b
  - cd b
  - time ../configure --enable-gcc-warnings
  - make -j$(nproc) syntax-check
  - time make -j$(nproc) V=1 check VERBOSE=t

Mingw32:
  image: debian:11-slim
  stage: test
  needs: [B-Guix]
  before_script:
  - dpkg --add-architecture i386
  - apt-get update -qq
  - apt-get install -y -qq make mingw-w64 wine wine32 wine64 libwine libwine:i386 binfmt-support wine-binfmt
  - update-binfmts --enable wine
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure --host=i686-w64-mingw32 CC='i686-w64-mingw32-gcc -static-libgcc' CPPFLAGS=-D_FORTIFY_SOURCE=0
  - make -j$(nproc) V=1
  - make -j$(nproc) -C liboath/tests check VERBOSE=t
  - make -j$(nproc) -C oathtool/tests check VERBOSE=t

Mingw64:
  image: debian:11-slim
  stage: test
  needs: [B-Guix]
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make mingw-w64 wine wine64 binfmt-support wine-binfmt
  - update-binfmts --enable wine
  script:
  - tar xfa out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfa out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - ./configure --host=x86_64-w64-mingw32 CPPFLAGS=-D_FORTIFY_SOURCE=0
  - make -j$(nproc) V=1
  - make -j$(nproc) -C liboath/tests check VERBOSE=t
  - make -j$(nproc) -C oathtool/tests check VERBOSE=T

OpenBSD:
  tags: [ openbsd ]
  needs: [B-Guix]
  stage: test
  before_script:
  - id
  - uname -a
  - sysctl hw
  script:
  - tar xfz out/b-guix/oath-toolkit-*.tar.gz
  - cd $(tar tfz out/b-guix/oath-toolkit-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings --with-xmlsec-crypto-engine=gnutls
  - time make check V=1 VERBOSE=t
  - grep '^PASS tst_oathtool' oathtool/tests/tst_oathtool.sh.log
  - grep '^PASS tst_validate' libpskc/tests/tst_validate.log

.pages:
  image: alpine:latest
  stage: build
  needs: ["Website", "B-Debian13-coverage", "B-Fedora39-clanganalyzer"]
  script:
  - mkdir public
  - mv out/b-debian13-coverage/coverage/ public/
  - mv out/b-fedora39-clanganalyzer/clang-analyzer public/
  - mv out/website/html/* public/
  artifacts:
    paths:
    - public
    expire_in: 30 days

pages:
  extends: .pages
  rules:
  - if: $CI_COMMIT_REF_PROTECTED == "true"

pages-test:
  extends: .pages
  rules:
  - if: $CI_COMMIT_REF_PROTECTED != "true"
